### ISSUE TITLE
Leverage Khaos?

### ISSUE THREAD

**Issue by rmarscher** [shoptology/boilerplate#6]
Just came across this tool where you point it at a git repo that treats all of the source files in it as handlebars templates. Seems it could be useful to update this project to work with it. http://khaos.io/

**Comment by adamisme** [comment]
Lol Almost 10 years later.

**Comment by rmarscher** [comment]
I figured it's probably not happening :joy:

**Comment by gospace** [comment]
lol. This made my night. 😂 How are you guys doing‽‽‽

**Comment by rmarscher** [comment]
Haha! Catching up over an old github issue. Doing great! I love that this still works - https://www.gpj.com/dreamforce-infographic/ -  It was a project James and I did when we were trying to find a home at GPJ. Anyway. Cheers!

**Comment by gospace** [comment]
I love it. :)

What are you up to these days?
